name: 'Publish python package'
author: 'David S.'
description: 'Publishes python packages that use poetry'
inputs:
  pypi_username:
    description: 'pypi username'
    required: true
  pypi_password:
    description: 'pypi password'
    required: true
  poetry_build_args:
    description: 'additional arguments to send to poetry build'
    required: false
    default: ''
  twine_upload_args:
    description: 'additional arguments to send to twine upload'
    required: false
    default: ''
branding:
  color: yellow
  icon: upload-cloud
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.pypi_username }}
  - ${{ inputs.pypi_password }}
  - ${{ inputs.poetry_build_args }}
  - ${{ inputs.twine_upload_args }}